import os
from datetime import datetime
import json
from typing import Dict, Any, List

class ReportGenerator:
    """
    Generates Markdown reports from Janus analysis results.
    """
    
    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

    def generate_report(self, result: Dict[str, Any]) -> str:
        """
        Creates a markdown report file and returns the path.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        mode_str = "forward" if "Forward" in result.get("mode", "") else "backward"
        filename = f"janus_report_{mode_str}_{timestamp}.md"
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(f"# 🎭 Janus Analysis Report\n\n")
            f.write(f"- **Mode:** {result.get('mode', 'Unknown')}\n")
            f.write(f"- **Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"- **Target Claim:**\n> {result.get('target_claim', 'N/A')}\n\n")
            
            analysis = result.get("match_analysis", {})
            risk_level = analysis.get("risk_level", "UNKNOWN")
            risk_score = analysis.get("risk_score", 0.0)
            
            emoji = "🚨" if risk_score > 0.6 else "⚠️" if risk_score > 0.3 else "✅"
            
            f.write(f"## 📊 Overall Risk: {emoji} {risk_level} ({risk_score:.0%})\n\n")

            if result.get("ai_opinion"):
                f.write(f"### 🎯 Agent Expert Opinion\n\n")
                f.write(f"{result['ai_opinion']}\n\n")
            
            f.write(f"### 🧩 Match Details\n\n")
            f.write("| Element ID | Status | Matching Patents | Top Similarity |\n")
            f.write("|------------|--------|------------------|----------------|\n")
            
            matches = analysis.get("matches", {})
            details = analysis.get("match_details", {})
            
            # Note: We need the full element list to show missing ones too
            # For simplicity in this reporter, we use the matches dict
            for el_id, patent_ids in matches.items():
                status = "✅ Found" if patent_ids else "❌ Missing"
                patents_str = ", ".join(patent_ids) if patent_ids else "-"
                
                # Find max score for this element
                max_score = 0.0
                for k, v in details.items():
                    if k.startswith(f"{el_id}:"):
                        max_score = max(max_score, v)
                
                f.write(f"| {el_id} | {status} | {patents_str} | {max_score:.2f} |\n")
            
            missing = analysis.get("missing_elements", [])
            if missing:
                f.write(f"\n**Missing Elements:** {', '.join(missing)}\n")
            
            if "amendment_proposal" in result and result["amendment_proposal"]:
                ap = result["amendment_proposal"]
                f.write(f"\n## 🛡️ Suggested Amendment\n\n")
                f.write(f"**Strategy:** {ap.get('strategy')}\n")
                f.write(f"**Amended Claim:**\n\n```text\n{ap.get('amended_claim')}\n```\n\n")
                f.write(f"**Reasoning:** {ap.get('reasoning')}\n")
            
            elif "correction_proposal" in result and result["correction_proposal"]:
                cp = result["correction_proposal"]
                f.write(f"\n## 🛡️ Correction Proposal\n\n")
                f.write(f"**Original Risk:** {cp.get('original_risk')}\n")
                f.write(f"**Suggested Amendment:**\n\n```text\n{cp.get('suggested_amendment')}\n```\n\n")
                f.write(f"**Reasoning:** {cp.get('reasoning')}\n")
            
            f.write(f"\n---\n*Generated by Janus Project*")
            
        return filepath

    def generate_dashboard(self, result: Dict[str, Any], elements: List[Dict[str, Any]]) -> str:
        """
        Creates an interactive HTML dashboard report.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"janus_dashboard_{timestamp}.html"
        filepath = os.path.join(self.output_dir, filename)
        
        template_path = os.path.join(os.path.dirname(__file__), "templates", "dashboard_template.html")
        with open(template_path, "r", encoding="utf-8") as f:
            html = f.read()

        # Prepare Data for Dashboard
        analysis = result.get("match_analysis", {})
        dashboard_data = {
            "risk_score": analysis.get("risk_score", 0.0),
            "matches": analysis.get("matches", {}),
            "match_details": analysis.get("match_details", {}),
            "elements": elements
        }

        # Inject Data
        html = html.replace("{{REPORT_ID}}", timestamp)
        html = html.replace("{{DATE}}", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        html = html.replace("{{TARGET_CLAIM}}", result.get("target_claim", "N/A"))
        html = html.replace("{{AI_OPINION}}", result.get("ai_opinion", "N/A"))
        html = html.replace("{{DATA_JSON}}", json.dumps(dashboard_data))

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

        return filepath
